import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { effectiveStatus, type Client, type DocumentRequest } from "@/lib/types";
import { StatusBadge } from "@/components/status-badge";

export default async function DashboardPage() {
  const { supabase } = await requireUser();
  const { data: clientsData } = await supabase.from("clients").select("*").order("created_at", { ascending: false });
  const clients = (clientsData || []) as Client[];
  const { data: requestsData } = await supabase.from("document_requests").select("*");
  const requests = (requestsData || []) as DocumentRequest[];
  const byClient = new Map<string, DocumentRequest[]>();
  requests.forEach(request => byClient.set(request.client_id, [...(byClient.get(request.client_id) || []), request]));
  const statuses = requests.map(effectiveStatus);
  const pending = statuses.filter(s => s === "pending").length; const overdue = statuses.filter(s => s === "overdue").length;
  const complete = clients.filter(client => { const docs = byClient.get(client.id) || []; return docs.length > 0 && docs.every(d => effectiveStatus(d) === "received"); }).length;
  return <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-indigo-600">Overview</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Your client requests</h1><p className="mt-2 text-slate-600">Stay ahead of every document you are waiting for.</p></div><Link className="button-primary" href="/clients/new">+ Add client</Link></div><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Clients", clients.length, "Total clients in your firm"], ["Pending", pending, "Documents awaiting receipt"], ["Overdue", overdue, "Past their due date"], ["Complete", complete, "Clients with all documents received"]].map(([label, value, help]) => <div className="card p-5" key={String(label)}><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight">{value}</p><p className="mt-2 text-xs text-slate-500">{help}</p></div>)}</section><section className="card mt-8 overflow-hidden"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Priority clients</h2><p className="mt-1 text-sm text-slate-500">Clients with outstanding document requests.</p></div><Link className="text-sm font-semibold text-indigo-600 hover:text-indigo-700" href="/clients">View all</Link></div>{clients.length === 0 ? <div className="px-5 py-12 text-center"><h3 className="font-semibold">No clients yet</h3><p className="mt-2 text-sm text-slate-500">Add your first client to start tracking their documents.</p><Link href="/clients/new" className="button-primary mt-5">Add your first client</Link></div> : <div className="divide-y">{clients.slice(0, 6).map(client => { const docs = byClient.get(client.id) || []; const clientStatuses = docs.map(effectiveStatus); const clientOverdue = clientStatuses.filter(s => s === "overdue").length; const clientPending = clientStatuses.filter(s => s === "pending").length; const state = clientOverdue ? "overdue" : clientPending ? "pending" : "received"; const summary = clientOverdue ? `${clientOverdue} overdue` : clientPending ? `${clientPending} pending` : docs.length ? "Complete" : "No requests yet"; return <Link href={`/clients/${client.id}`} className="flex items-center justify-between gap-4 px-5 py-4 hover:bg-slate-50" key={client.id}><div><p className="font-medium">{client.company_name || client.name}</p><p className="mt-1 text-sm text-slate-500">{client.email || "No email added"}</p></div><div className="flex items-center gap-3"><span className="hidden text-sm text-slate-500 sm:inline">{summary}</span>{docs.length > 0 && <StatusBadge status={state} />}</div></Link>; })}</div>}</section></>;
}
