import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { effectiveStatus, type Client, type DocumentRequest } from "@/lib/types";
import { StatusBadge } from "@/components/status-badge";

export default async function ClientsPage() {
  const { supabase } = await requireUser();
  const { data: clientsData } = await supabase.from("clients").select("*").order("created_at", { ascending: false }); const clients = (clientsData || []) as Client[];
  const { data: requestsData } = await supabase.from("document_requests").select("*"); const requests = (requestsData || []) as DocumentRequest[];
  return <><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-medium text-indigo-600">Clients</p><h1 className="mt-1 text-3xl font-bold tracking-tight">All clients</h1><p className="mt-2 text-slate-600">Every client and their document status in one place.</p></div><Link className="button-primary shrink-0" href="/clients/new">+ Add client</Link></div><div className="card mt-8 overflow-x-auto">{clients.length === 0 ? <div className="py-14 text-center"><h2 className="font-semibold">Your client list is empty</h2><p className="mt-2 text-sm text-slate-500">Add a client, then create the documents you need from them.</p><Link className="button-primary mt-5" href="/clients/new">Add client</Link></div> : <table className="min-w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-semibold">Client</th><th className="px-5 py-3 font-semibold">Contact</th><th className="px-5 py-3 font-semibold">Requests</th><th className="px-5 py-3 font-semibold">Added</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y">{clients.map(client => { const docs = requests.filter(r => r.client_id === client.id).map(effectiveStatus); const pending = docs.filter(s => s === "pending").length; const received = docs.filter(s => s === "received").length; const overdue = docs.filter(s => s === "overdue").length; return <tr key={client.id} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-medium">{client.company_name || client.name}</p></td><td className="px-5 py-4 text-slate-600"><p>{client.email || "—"}</p><p className="mt-1">{client.phone || "—"}</p></td><td className="px-5 py-4"><div className="flex flex-wrap gap-1.5">{pending > 0 && <StatusBadge status="pending" />}{overdue > 0 && <StatusBadge status="overdue" />}{received > 0 && <StatusBadge status="received" />}<span className="self-center text-xs text-slate-500">{docs.length === 0 ? "No requests" : `${pending} pending · ${received} received · ${overdue} overdue`}</span></div></td><td className="whitespace-nowrap px-5 py-4 text-slate-600">{new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(client.created_at))}</td><td className="px-5 py-4 text-right"><Link className="font-semibold text-indigo-600 hover:text-indigo-700" href={`/clients/${client.id}`}>Open</Link></td></tr>; })}</tbody></table>}</div></>;
}
